name = "xboxapi-workers"
main = "src/index.ts"
compatibility_date = "2024-05-12"

kv_namespaces = [
    { binding = "TOKEN_STORE", id = "" },
#    { binding = "PROFILES_CACHE", id = "" }, # (Optional) Used to reduce responses time
]

[secrets]
XBOX_ACCESS_TOKEN = ""
XBOX_REFRESH_TOKEN = ""

# Microsoft Azure credentials. See https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app
MS_CLIENT_ID = ""
MS_CLIENT_SECRET = ""

# WEBHOOK_URL = ""
